# Generated by Django 3.1.2 on 2020-10-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201026_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='project_owner',
        ),
    ]
