# Generated by Django 3.1.2 on 2020-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
